import { Hono, type Context } from 'hono';
import type { Bindings } from '../types.js';
import { queueWebhookAndWakeUp } from './coordination.js';

function parseFormData(formData: FormData): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const [key, value] of formData.entries()) {
    if (key.endsWith('[]')) {
      const baseKey = key.slice(0, -2);
      if (!result[baseKey]) {
        result[baseKey] = [];
      }
      (result[baseKey] as unknown[]).push(value);
    } else if (result[key] !== undefined) {
      if (!Array.isArray(result[key])) {
        result[key] = [result[key]];
      }
      (result[key] as unknown[]).push(value);
    } else {
      result[key] = value;
    }
  }
  return result;
}

const system = new Hono<{ Bindings: Bindings }>();

/**
 * Built-in webhook for page form submissions.
 * This handles form POSTs from pages generated by .page() steps.
 *
 * POST /webhooks/system/page-form?identifier=<identifier>&token=<token>
 * Content-Type: application/x-www-form-urlencoded or multipart/form-data
 */
system.post('/page-form', async (context: Context) => {
  const identifier = context.req.query('identifier');
  const token = context.req.query('token');

  if (!identifier) {
    return context.json(
      { error: 'Missing required query parameter "identifier"' },
      400
    );
  }

  // System page-form endpoint always requires a CSRF token
  if (!token) {
    return context.json(
      {
        received: false,
        action: 'ignored',
        identifier,
        reason: 'Missing form token',
      },
      403
    );
  }

  try {
    const formData = await context.req.formData();
    const response = parseFormData(formData);

    const result = await queueWebhookAndWakeUp(
      context,
      'page-form',
      identifier,
      response,
      token
    );

    // Return 403 if token mismatch
    if (result.action === 'ignored' && result.reason === 'Invalid form token') {
      return context.json(result, 403);
    }

    // Return 404 if no brain was waiting
    if (result.action === 'not_found') {
      return context.json(
        {
          ...result,
          message: 'No brain waiting for this form submission',
        },
        404
      );
    }

    return context.json(result);
  } catch (error) {
    console.error('Error processing page form submission:', error);
    return context.json({ error: 'Failed to process form submission' }, 500);
  }
});

export default system;
