import { Hono, type Context } from 'hono';
import type { Bindings } from '../types.js';
import { findAndResumeBrain, parseFormData } from './coordination.js';

const system = new Hono<{ Bindings: Bindings }>();

/**
 * Built-in webhook for UI form submissions.
 * This handles form POSTs from pages generated by .ui() steps.
 *
 * POST /webhooks/system/ui-form?identifier=<identifier>
 * Content-Type: application/x-www-form-urlencoded or multipart/form-data
 */
system.post('/ui-form', async (context: Context) => {
  const identifier = context.req.query('identifier');

  if (!identifier) {
    return context.json({ error: 'Missing required query parameter "identifier"' }, 400);
  }

  try {
    const formData = await context.req.formData();
    const response = parseFormData(formData);

    const result = await findAndResumeBrain(context, 'ui-form', identifier, response);

    // Return 404 if no brain was waiting
    if (result.action === 'not_found') {
      return context.json({
        ...result,
        message: 'No brain waiting for this form submission',
      }, 404);
    }

    return context.json(result);
  } catch (error) {
    console.error('Error processing UI form submission:', error);
    return context.json({ error: 'Failed to process form submission' }, 500);
  }
});

export default system;
