name = "cloudflare-test-project-worker" # Name for the worker in tests
main = "../dist/src/api.js" # Correct: Point to the BUILT Hono API entry point from the library
compatibility_date = "2024-04-05" # Use a recent date

# Define where the test D1 database lives
[[d1_databases]]
binding = "DB" # The binding name used in the code (env.DB)
database_name = "test-db-for-vitest"
database_id = "test-db-for-vitest" # Miniflare/Vitest uses this ID for local persistence
preview_database_id = "test-db-for-vitest" # Use the same for preview/local

# Define the Durable Object binding
[[durable_objects.bindings]]
name = "DO_NAMESPACE" # The binding name used in the code (env.DO_NAMESPACE)
class_name = "WorkflowDO" # The *exported* class name from the script below

# Specify migrations for the DO if needed (unlikely for basic tests initially)
# [[migrations]]
# tag = "v1" # required
# new_classes = ["WorkflowDO"] # required

[build]
# Command to build the worker (if needed, often inferred or handled by Vitest/Wrangler)
# command = "npm run build"
# Specifies the module rules for the build output.
# This is important to tell wrangler where to find the DO class.
# We point it to the library's built index file which should export WorkflowDO.
# Adjust the path relative to this wrangler.toml if the library build output differs.
module_rules = [
  { type = "ESModule", glob = "**/*.ts", fallthrough = true },
  # Point to the main library's output directory (where WorkflowDO is exported)
  # This assumes the library builds to ../dist/src/index.js relative to test-project/
  { type = "ESModule", glob = ["../dist/src/index.js"] }
]

[vars]
# Define any environment variables needed for tests here
# EXAMPLE_VAR = "example_value"